services:

  streamlit_app:
    image: ${IMAGE_NAME}
    build: .
    env_file:
      - ${ENV_FILE}
    depends_on:
      - traefik
    labels:
      # Base setup
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit_app.rule=Host(`${DOMAIN}`, `www.${DOMAIN}`)"  # Host address
      - "traefik.http.services.streamlit_app.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.streamlit_app.entrypoints=web"  # Use the HTTP entry point (web)
      # Rate Limiting Middleware
      - "traefik.http.middlewares.streamlit_app_ratelimit.ratelimit.average=20"
      - "traefik.http.middlewares.streamlit_app_ratelimit.ratelimit.burst=7"
      - "traefik.http.middlewares.streamlit_app_ratelimit.ratelimit.period=1m"
      # Apply the middleware to the router
      - "traefik.http.routers.streamlit_app.middlewares=streamlit_app_ratelimit@docker"
    networks:
      - bogdanko_network
    command: streamlit run app/01_Home.py --server.port=${PORT} --server.address=0.0.0.0
    restart: unless-stopped  # Auto restart container if not stopped manually
    deploy:
      resources:
        limits:
          memory: 600M  # Limit memory usage
        reservations:
          memory: 300M  # Soft memory limit

  traefik:
    image: traefik:v2.10
    command:
      # Base setup
      - "--log.level=DEBUG"  # Debug tools
      - "--providers.docker=true"  # Out of the box settings
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"  # Listen ports (http)
      - "--entrypoints.websecure.address=:443"  # Listen ports (https)
    ports:
      - "80:80"  # Open ports (http)
      - "443:443"  # Open ports (https)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Out of the box settings
      - "./letsencrypt:/letsencrypt"  # Storage for SSL certificates
    networks:
      - bogdanko_network
    restart: unless-stopped  # Auto restart container if not stopped manually
    deploy:
      resources:
        limits:
          memory: 400M  # Limit memory usage
        reservations:
          memory: 200M  # Soft memory limit

  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_TOKEN}
    restart: unless-stopped  # Auto restart container if not stopped manually
    deploy:
      resources:
        limits:
          memory: 500M  # Limit memory usage
        reservations:
          memory: 250M  # Soft memory limit


volumes:
  netdataconfig:
  netdatalib:
  netdatacache:


networks:
  bogdanko_network:
    driver: bridge
