services:

  streamlit_app:
    image: ${IMAGE_NAME}
    build: .
    env_file:
      - ${ENV_FILE}
    depends_on:
      - traefik
    labels:
      # Base setup
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit_app.rule=HostRegexp(`${DOMAIN}`)"  # Host address
      - "traefik.http.services.streamlit_app.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.streamlit_app.entrypoints=web"  # Use the HTTP entry point (web)
    networks:
      - bogdanko_network
    command: streamlit run app/01_Home.py --server.port=${PORT} --server.address=0.0.0.0

  traefik:
    image: traefik:v2.10
    command:
      # Base setup
      - "--log.level=DEBUG"  # Debug tools
      - "--providers.docker=true"  # Out of the box settings
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"  # Listen ports (http)
      - "--entrypoints.websecure.address=:443"  # Listen ports (https)
    ports:
      - "80:80"  # Open ports (http)
      - "443:443"  # Open ports (https)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Out of the box settings
      - "./letsencrypt:/letsencrypt"  # Storage for SSL certificates
    networks:
      - bogdanko_network

networks:
  bogdanko_network:
    driver: bridge
