services:

  streamlit_app:
    image: ${IMAGE_NAME}:${TAG}
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - traefik
    labels:
      # Base setup
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit_app.rule=HostRegexp(`${DOMAIN}`)"  # Host address
      - "traefik.http.services.streamlit_app.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.streamlit_app.entrypoints=web"  # Use the HTTP entry point (web)
      # Rate Limiting Middleware
      - "traefik.http.middlewares.streamlit_app_ratelimit.ratelimit.average=20"
      - "traefik.http.middlewares.streamlit_app_ratelimit.ratelimit.burst=7"
      - "traefik.http.middlewares.streamlit_app_ratelimit.ratelimit.period=1m"
      # Apply the middleware to the router
      - "traefik.http.routers.streamlit_app.middlewares=streamlit_app_ratelimit@docker"
    command: streamlit run app/01_Home.py --server.port=${PORT} --server.address=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 600M  # Limit memory usage
        reservations:
          memory: 300M  # Soft memory limit

  traefik:
    image: traefik:v2.10
    command:
      - "--log.level=DEBUG"  # Debug tools
      - "--api.insecure=true"  # Debug tools
      - "--api.dashboard=true"  # Debug tools
      - "--providers.docker=true"  # Out of the box settings
      - "--providers.docker.exposedbydefault=false"  # Out of the box settings
      - "--entrypoints.web.address=:80"  # Listen ports (http)
      - "--entrypoints.websecure.address=:443"  # Listen ports (https)
    ports:
      - "80:80"  # Open ports (http)
      - "443:443"  # Open ports (https)
      - "8080:8080"  # Traefik console
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Out of the box settings
      - "./letsencrypt:/letsencrypt"  # Storage for SSL certificates
    deploy:
      resources:
        limits:
          memory: 400M  # Limit memory usage
        reservations:
          memory: 200M  # Soft memory limit

  new_relic:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "${NEW_RELIC_KEY}"
    restart: unless-stopped
